//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canswer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public int ID { get; set; }
        public string TreatmentName { get; set; }
        public string Treatment_Link { get; set; }
        public Nullable<int> treatmenttypeID { get; set; }
        public Nullable<int> WHO_added { get; set; }
    
        public virtual Treatment_Type Treatment_Type { get; set; }
        public virtual User User { get; set; }
    }
}
