//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF354API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int ID { get; set; }
        public Nullable<int> Answer1 { get; set; }
        public Nullable<int> C_User { get; set; }
        public string FA_Answer { get; set; }
        public Nullable<int> downvote { get; set; }
        public Nullable<int> upvote { get; set; }
    
        public virtual User User { get; set; }
        public virtual Question Question { get; set; }
    }
}
