//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF354API.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Post_Comment = new HashSet<Post_Comment>();
        }
    
        public int ID { get; set; }
        public string Post_Description { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<System.DateTime> Post_DateAdded { get; set; }
        public Nullable<bool> archive { get; set; }
        public Nullable<int> WHO_add { get; set; }
        public HttpPostedFileBase inputfield { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post_Comment> Post_Comment { get; set; }
    }
}
