//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF354API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> FreqID { get; set; }
        public Nullable<int> Client { get; set; }
    
        public virtual Frequency Frequency { get; set; }
        public virtual User User { get; set; }
    }
}
