//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canswer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_Comment
    {
        public int ID { get; set; }
        public string Post_Comment1 { get; set; }
        public Nullable<int> Post_ID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
